
services:
  server-db:
    image: postgres:15
    container_name: server-db
    restart: unless-stopped
    ports:
      - "5434:5432"   # host:container
    environment:
      POSTGRES_USER: server_user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: server_db
    volumes:
      - server_data:/var/lib/postgresql/data

volumes:
  server_data:
